// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu-GDqbDlYHFMDAfM_L9TdDc7Txk1qInU',
    appId: '1:397959128378:web:8ec7677763bd9ca940dc03',
    messagingSenderId: '397959128378',
    projectId: 'evenly-c18-dokki',
    authDomain: 'evenly-c18-dokki.firebaseapp.com',
    storageBucket: 'evenly-c18-dokki.firebasestorage.app',
    measurementId: 'G-XNM4CXCPK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU4RUcUMD8G7BoKgGk0dih42Ai4qeVcnw',
    appId: '1:397959128378:android:84d6b180ea3f4a7040dc03',
    messagingSenderId: '397959128378',
    projectId: 'evenly-c18-dokki',
    storageBucket: 'evenly-c18-dokki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz7J4XqpiJrRy25cYeayTpWSO1Azywctc',
    appId: '1:397959128378:ios:1f7ebb1fb6e2e0e340dc03',
    messagingSenderId: '397959128378',
    projectId: 'evenly-c18-dokki',
    storageBucket: 'evenly-c18-dokki.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC18Dokki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz7J4XqpiJrRy25cYeayTpWSO1Azywctc',
    appId: '1:397959128378:ios:1f7ebb1fb6e2e0e340dc03',
    messagingSenderId: '397959128378',
    projectId: 'evenly-c18-dokki',
    storageBucket: 'evenly-c18-dokki.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC18Dokki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu-GDqbDlYHFMDAfM_L9TdDc7Txk1qInU',
    appId: '1:397959128378:web:c7513032ad24d42540dc03',
    messagingSenderId: '397959128378',
    projectId: 'evenly-c18-dokki',
    authDomain: 'evenly-c18-dokki.firebaseapp.com',
    storageBucket: 'evenly-c18-dokki.firebasestorage.app',
    measurementId: 'G-4F8RC4PK18',
  );
}
